CFLAGS+=-I$(SCU_DIR)

.PHONY: test build clean

test: build
	$(SCU_DIR)/testrunner $(TESTCASES)

test-gdb: build
	$(SCU_DIR)/testrunner --gdb $(TESTCASES)

test-valgrind: build
	$(SCU_DIR)/testrunner --valgrind $(TESTCASES)

build: $(TESTCASES)

clean::
	rm -f $(TESTCASES) $(patsubst %,%.o,$(TESTCASES)) $(patsubst %,valgrind.%.log,$(TESTCASES))

$(TESTCASES): %:%.o
	$(CC) -o $@ $< $(SCU_DIR)/scu.c -Wl,$(SCU_DIR)/testcases.lds $(CFLAGS)

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS)
