CFLAGS+=-Wall -I$(SCU_DIR)

.PHONY: test build clean

test: build
	python $(SCU_DIR)/testrunner.py $(TESTCASES)

build: $(TESTCASES)

clean::
	rm -f $(TESTCASES) $(patsubst %,%.o,$(TESTCASES))

$(TESTCASES): %:%.o
	$(CC) -o $@ $< $(SCU_DIR)/scu.c -ljansson -Wl,$(SCU_DIR)/testcases.lds

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS)
