CFLAGS+=-I$(SCU_DIR)/libscu-c/

.PHONY: test build clean

test: build
	$(SCU_DIR)/testrunner $(TESTCASES)

test-gdb: build
	$(SCU_DIR)/testrunner --gdb $(TESTCASES)

test-valgrind: build
	$(SCU_DIR)/testrunner --valgrind $(TESTCASES)

build: $(TESTCASES)

clean::
	rm -f $(TESTCASES) $(patsubst %,%.o,$(TESTCASES)) $(patsubst %,valgrind.%.log,$(TESTCASES))

$(TESTCASES): %:%.o
	$(CC) -o $@ $< -L$(SCU_DIR)/libscu-c/ -lscu-c

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS)
